name: Lint, test on every commit

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
    - name: Lint with flake8
        run: |
          flake8 . --count --select=E4,E7,E9,F4,F63,F7,F82,F401,F901 --show-source --max-line-length=127 --statistics
    - name: Test with pytest
        run: |
          pytest --cov-config=./tests/.coveragerc --cov --cov-fail-under=60
    - name: Build
        env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
            python setup.py sdist bdist_wheel
            # twine upload dist/* FOR UPLOADING PURPOSES

