# This is a basic workflow to help you get started with Actions

name: Upload to TestPyPI

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version tag'
        default: 'v0.1.0'
        required: true  # Triggers the workflow on push to the master branch
  #push:
  #  branches:
  #    - feature/159-pypi


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install build deps
          python3 -m pip install setuptools wheel twine

      - name: "Tag Release"
        run: |
          git tag ${{ github.event.inputs.release-version }}
          git push --tags

      # Upload to TestPyPI
      - name: Build and Upload to TestPyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi

      - name: "Remove test tag"
        run: |
          git push --delete origin ${{ github.event.inputs.release-version }}